# Generated by Django 6.0.2 on 2026-02-24 06:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='rooms'),
        ),
    ]
